### ISSUE TITLE
Timeline for releasing synthetic data used for experiments?

### ISSUE THREAD

**Issue by vishaal27** [BAAI-DCAI/Training-Data-Synthesis#1]
Hey, thanks for the great work, and for open-sourcing your code. Do you have an estimated timeline of when you plan to release the synthetic dataset you generated?

**Comment by YuanJianhao508** [comment]
Hi @vishaal27,

Thanks for your interest in our work! We plan to release it shortly, probably over the next week. We'll notify you in this issue when it's ready.

**Comment by YuanJianhao508** [comment]
Hi @vishaal27,

We have released the generated synthetic data, they can now be download from the huggingface (please see the updated readme file
